version: '3'
services:
  gsm-php5:
    image: "webdevops/php-apache:alpine-php5"
    restart: always
    links: 
    - gsm-mysql:mysql
    ports: 
    - 8080:80
    volumes:
    - .:/app

  gsm-mysql:
    image: "mysql:5"
    restart: always
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - ./mysql:/var/lib/mysql